### ISSUE TITLE
Module isn't available on packagist.org

### ISSUE THREAD

**Issue by yuriichayka** [Datatrics/magento2-integration#1]
Can't install the module via composer. 
Seems it just isn't available on packagist.

Error I've got:
  "Could not find a matching version of package datatrics/magento2-integration. Check the package spelling, your version constraint and that the package is available in a stability which matches y  
  our minimum-stability (stable). "

**Comment by Marvin-Magmodules** [comment]
Hi @yuriichayka, thank you for opening this issue. I'm happy to tell you the module is available on packagist/composer since this morning. We are closing this issue now but please feel free to reopen the issue if this still occurs.
