### ISSUE TITLE
Customer Grid SQL error

### ISSUE THREAD

**Issue by ghost** [Datatrics/magento2-integration#19]
**Describe the bug**
Sql error when using filter customer_grid filter backend

**Used versions**
- Magento 2.3.7
- Datatrics 1.3.5

**To Reproduce**
1. Go to magento admin
2. Go to customers
3. Filter on customer name

`[2021-06-18 09:03:30] report.CRITICAL: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'main_table.main_table.name' in 'where clause', query was: SELECT COUNT(*) FROM `customer_grid_flat` AS `main_table`
 LEFT JOIN `directory_country_region` AS `rct` ON rct.region_id=`main_table`.`billing_region_id`
 LEFT JOIN `directory_country_region_name` AS `rnt` ON rnt.region_id=`main_table`.`billing_region_id` AND rnt.locale='en_US'
 LEFT JOIN `datatrics_profile` ON datatrics_profile.customer_id = main_table.entity_id WHERE (`main_table`.`main_table`.`name` LIKE '%Marieke%') {"exception":"[object] (Zend_Db_Statement_Exception(code: 42): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'main_table.main_table.name' in 'where clause', query was: SELECT COUNT(*) FROM `customer_grid_flat` AS `main_table`
 LEFT JOIN `directory_country_region` AS `rct` ON rct.region_id=`main_table`.`billing_region_id`
 LEFT JOIN `directory_country_region_name` AS `rnt` ON rnt.region_id=`main_table`.`billing_region_id` AND rnt.locale='en_US'
 LEFT JOIN `datatrics_profile` ON datatrics_profile.customer_id = main_table.entity_id WHERE (`main_table`.`main_table`.`name` LIKE '%Marieke%') at /data/web/magento2/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'main_table.main_table.name' in 'where clause' at /data/web/magento2/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91)"} []
`

**Expected behavior**
No sql error when filtering.

**Actual behavior**
Sql error

**Screenshots**
Nvt

**Additional context**
Nvt

**Comment by ghost** [comment]
Maintable prefix is applied twice

vendor/datatrics/magento2-integration/Plugin/CustomerGridCollection.php

**` public function afterSearch($intercepter, $collection)
    {
        if ($collection->getMainTable() === $collection->getConnection()->getTableName(self::TABLE)) {
            $leftJoinTableName = $collection->getConnection()->getTableName(ProfileResource::ENTITY_TABLE);

            $collection
                ->getSelect()
                ->joinLeft(
                    ['datatrics_profile' => $leftJoinTableName],
                    "datatrics_profile.customer_id = main_table.entity_id",
                    ['status']
                );
            $where = $collection->getSelect()->getPart(\Magento\Framework\DB\Select::WHERE);
            foreach ($where as &$item) {
                if (strpos($item, 'status') === false) {
                    $item = substr_replace($item, "`main_table`.", strpos($item, '`'), 0);
                }
            }
            $collection->getSelect()->setPart(\Magento\Framework\DB\Select::WHERE, $where);
            $collection->addFilterToMap('status', 'datatrics_profile.status');
        }
        return $collection;
    }`**

**Comment by ghost** [comment]
@Marvin-Magmodules  Can you fix this?

**Comment by Frank-Magmodules** [comment]
HI @dheesbeen ,

We are happy to share that we've just released the new [1.3.6](https://github.com/Datatrics/magento2-integration/releases/tag/v1.3.6) version with a fix for the customer grid SQL issue. Thank you for the detailed issue report. We are closing this issue now but please feel free to reopen the issue if this still occurs.
