### ISSUE TITLE
Magento CE 2.4.5-p1

### ISSUE THREAD

**Issue by ZIPITRO** [Datatrics/magento2-integration#32]
**Describe the bug**
After installing Magento 2 Open Source(CE) 2.4.5-p1, we have the following error in var/log/system.log

**Used versions**
Magento 2.4.5-P1
CE(Open Source)
Module version number 1.6.2

**To Reproduce**
1. Update to Magento 2.4.5-p1
2. You will have directly this error in the system.log after loading a frontpage
3. See error : 

`[2022-10-13T20:53:53.720543+00:00] main.CRITICAL: TypeError: str_replace(): Argument #2 ($replace) must be of type array|string, float given in /data/web/m245/vendor/datatrics/magento2-integration/Service/Pixel/TemplatePreparator.php:46
Stack trace:
#0 /data/web/m245/vendor/datatrics/magento2-integration/Service/Pixel/TemplatePreparator.php(46): str_replace()
#1 /data/web/m245/vendor/datatrics/magento2-integration/Service/Pixel/TemplatePreparator.php(74): Datatrics\Connect\Service\Pixel\TemplatePreparator->applySimpleParameters()
#2 /data/web/m245/vendor/datatrics/magento2-integration/Service/Pixel/TemplatePreparator.php(33): Datatrics\Connect\Service\Pixel\TemplatePreparator->applyRecursiveParameters()
#3 /data/web/m245/vendor/datatrics/magento2-integration/ViewModel/PreProcessor.php(90): Datatrics\Connect\Service\Pixel\TemplatePreparator->execute()
#4 /data/web/m245/vendor/datatrics/magento2-integration/Controller/Cart/Get.php(72): Datatrics\Connect\ViewModel\PreProcessor->getTrack()
#5 /data/web/m245/vendor/magento/framework/Interception/Interceptor.php(58): Datatrics\Connect\Controller\Cart\Get->execute()
#6 /data/web/m245/vendor/magento/framework/Interception/Interceptor.php(138): Datatrics\Connect\Controller\Cart\Get\Interceptor->___callParent()
#7 /data/web/m245/vendor/magento/framework/Interception/Interceptor.php(153): Datatrics\Connect\Controller\Cart\Get\Interceptor->Magento\Framework\Interception\{closure}()
#8 /data/web/m245/generated/code/Datatrics/Connect/Controller/Cart/Get/Interceptor.php(23): Datatrics\Connect\Controller\Cart\Get\Interceptor->___callPlugins()
#9 /data/web/m245/vendor/magento/framework/App/Action/Action.php(111): Datatrics\Connect\Controller\Cart\Get\Interceptor->execute()
#10 /data/web/m245/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch()
#11 /data/web/m245/vendor/magento/framework/Interception/Interceptor.php(138): Datatrics\Connect\Controller\Cart\Get\Interceptor->___callParent()
#12 /data/web/m245/vendor/magento/framework/Interception/Interceptor.php(153): Datatrics\Connect\Controller\Cart\Get\Interceptor->Magento\Framework\Interception\{closure}()
#13 /data/web/m245/generated/code/Datatrics/Connect/Controller/Cart/Get/Interceptor.php(32): Datatrics\Connect\Controller\Cart\Get\Interceptor->___callPlugins()
#14 /data/web/m245/vendor/magento/framework/App/FrontController.php(245): Datatrics\Connect\Controller\Cart\Get\Interceptor->dispatch()
#15 /data/web/m245/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#16 /data/web/m245/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#17 /data/web/m245/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#18 /data/web/m245/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#19 /data/web/m245/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#20 /data/web/m245/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#21 /data/web/m245/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#22 /data/web/m245/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
#23 /data/web/m245/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#24 /data/web/m245/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#25 /data/web/m245/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#26 /data/web/m245/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#27 /data/web/m245/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
`

**Expected behavior**
No errors and a clean loading page

**Actual behavior**
Throws error and the module is not working, 500 error on checking cart, not all the time.
![datatrics-error-occured](https://user-images.githubusercontent.com/22952492/195711037-160f4812-2a56-49e4-ab45-4b945798b699.png)

Thanks for looking into it 👍

**Comment by Marvin-Magmodules** [comment]
HI @ZIPITRO  ,

We are happy to share that we've just released the new [1.6.3](https://github.com/Datatrics/magento2-integration/releases/tag/v1.6.3) version with a for this issue. Thank you for the detailed issue report. We are closing this issue now but please feel free to reopen the issue if this still occurs.
