### ISSUE TITLE
compatibility with  Baldwin/UrlDataIntegrityChecker

### ISSUE THREAD

**Issue by henkvalk** [Datatrics/magento2-integration#38]
**Describe the bug**

**Used versions**
- *Magento Version number(eg 2.4.2-p1)*:
- *Open source*:
- *Module version number (Check configuration)*: 1.6.5

**To Reproduce**
1. Install baldwin/magento2-module-url-data-integrity-checker
2. Click on 'Catalog > Data Integrity Checker > Product URL'
3. See error
```
Call to undefined method Baldwin\UrlDataIntegrityChecker\Model\ResourceModel\Catalog\Category\UrlKeyCollection\Interceptor::getMainTable()
Exception in /data/web/deployer_production/releases/14/app/code/Datatrics/Connect/Plugin/CustomerGridCollection.php:49
```
**Expected behavior**
Show the duplicated URLs

**Actual behavior**
Showing an error

**Screenshots**
![image](https://user-images.githubusercontent.com/8955854/233607753-3e019f73-6039-44da-8032-3b8c2377dc77.png)

**Comment by Frank-Magmodules** [comment]
Greetings @henkvalk, I appreciate you bringing this issue to our attention. I am happy to report that we have just launched version [1.6.6](https://github.com/Datatrics/magento2-integration/releases/tag/v1.6.6), which addresses the compatibility issues with external modules in Datatrics. While we will be closing this issue for now, please feel free to reopen it if you encounter any difficulties or have any additional inquiries. Thank you.
