### ISSUE TITLE
Sql error when using filter order_grid filter backend

### ISSUE THREAD

**Issue by thokiller** [Datatrics/magento2-integration#42]
**Describe the bug**
Sql error when using filter order_grid filter backend

**Used versions**
- *Magento Version 2.4.5-p3*:
- *Open source*:
- *module version 1.6.5*:

**To Reproduce**
1. Go to magento admin
2. Go to sales
3. Filter on Purchase Date

[2023-07-26T12:00:06.054947+00:00] report.CRITICAL: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous in /data/web/magento2/vendor/magento/frame
work/DB/Statement/Pdo/Mysql.php:90

Zend_Db_Statement_Exception: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous, query was: SELECT `main_table`.*, `datatrics_sales`.`status` AS `datatrics_status` FROM `sales_order_grid` AS `main_table`
 LEFT JOIN `datatrics_sales` ON main_table.entity_id = datatrics_sales.order_id WHERE  (((`created_at` >= '2023-07-24 22:00:00'))) AND (((`created_at` <= '2023-07-26 21:59:59'))) ORDER BY main_table.created_at DESC

**Expected behavior**
orders filterd by purchase date

**Actual behavior**
Sql error

**Screenshots**
NVT

**Additional context**
NVT

**Comment by Marvin-Magmodules** [comment]
Hi @thokiller, thank you for opening this issue. 

Happy to share that this was fixed in the latest version [v1.6.8](https://github.com/Datatrics/magento2-integration/releases/tag/v1.6.8). 

We refactored the grid collection by removing the `created_at` and joined the data from from the orders table due to an open issue in Magento 2.4.x, see https://github.com/magento/magento2/issues/36439

**Comment by Marvin-Magmodules** [comment]
Hi @thokiller any update on this issue, can you confirm this issue has been fixed by updating to to >= v1.6.8?

**Comment by Marvin-Magmodules** [comment]
Hi @thokiller, due to inactivity, I assume this is clear now and I will close the issue.
If the issue still appears or something is not clear, feel free to re-open this issue.
