### ISSUE TITLE
Add index on customer_id in datatrics_profile

### ISSUE THREAD

**Issue by marcoboom** [Datatrics/magento2-integration#5]
Please add an index to customer_id in the datatrics_profile. Our client has 500k+ customers and 10k+ records in datatrics_profile. The result is that the customer view in the Magento admin timeouts on the customer_grid_flat query.

**Comment by Marvin-Magmodules** [comment]
Hi @marcoboon, yes for sure! We are happy to share that we've just released the new [1.1.0](https://github.com/Datatrics/magento2-integration/releases/tag/v1.1.0) version which include a commit that adds an index to the customer_id field in the datatrics_profile table. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Comment by marcoboom** [comment]
Thanks @Marvin-Magmodules
