### ISSUE TITLE
'content_maintenance' CRON job fails on Magento EE. "Unknown column 'catalog_product_entity.product_id'"

### ISSUE THREAD

**Issue by yuriichayka** [Datatrics/magento2-integration#7]
**Describe the bug**
'content_maintenance' CRON job fails
Error is:
"_SQLSTATE[42S22]: Column not found: 1054 Unknown column 'catalog_product_entity.product_id' in 'field list', query was: SELECT `catalog_product_entity`.`product_id` FROM `catalog_product_entity` WHERE (catalog_product_entity.created_in <= '1601544660') AND (catalog_product_entity.updated_in > '1601544660'_)"

**Used versions**
- Magento Enterprise 2.3.5-p1;
- *Module version number (Check configuration)*: 1.0.3

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshots**

**Additional context**

**Comment by Marvin-Magmodules** [comment]
Hi @yuriichayka, we are happy to share that we've just released the new [v1.2.0](https://github.com/Datatrics/magento2-integration/releases/tag/v1.2.0) version with a fix for this issue. Thank you for the detailed report and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.
