### ISSUE TITLE
In customer admin, email filter is broken

### ISSUE THREAD

**Issue by evs-xsarus** [Datatrics/magento2-integration#8]
**Describe the bug**
In the customer admin, it's not possible to search on an emailaddress.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.3.4
- *Open source/Commerce/B2B*: Commerce
- *Module version number (Check configuration)*: 1.1.0

**To Reproduce**
1. Go to 'admin > customers'
2. Click on 'filter'
3. Specify an e-mailaddress to filter on 
4. Click on 'Apply filters'

**Expected behavior**
The customers with that emailaddress must be shown.

**Actual behavior**
The following error is shown:
> Something went wrong with processing the default view and we have restored the filter to its original state.

**Screenshots**

**Additional context**
I found this in the logs:

> SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'email' in where clause is ambiguous, query was: SELECT COUNT(DISTINCT main_table.entity_id) FROM `customer_grid_flat` AS `main_table`
 LEFT JOIN `datatrics_profile` ON datatrics_profile.customer_id = main_table.entity_id WHERE (`email` LIKE '%evs-xsarus@aaaa.nl%') at /sites/dlk/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110

**Comment by Marvin-Magmodules** [comment]
Hi @evs-xsarus, we are happy to share that we've just released the new [v1.2.0](https://github.com/Datatrics/magento2-integration/releases/tag/v1.2.0) version with a fix for this issue. Thank you for the detailed report and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.
